spring:
  application:
    name: demo

server:
  port: 1337

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

zuul:
  host:
    connect-timeout-millis: 500000
    socket-timeout-millis: 500000
  ignoredServices: '*'
  routes:
    demo:
      path: /demo/**
      url: http://localhost:6666/api

